
    <?php
    $form = $this->filter_form;
    $form->prepare();
    ?>

    <h3>Отделы</h3>
    <?php echo $this->form()->openTag($form);?>
    <?php echo $this->formRow($form->get('departments')); ?>

    <h3>Языки</h3>
    <?php echo $this->formRow($form->get('languages')); ?>
    <br/>
    <?php echo $this->formSubmit($form->get('submit')); ?>
    <?php echo $this->form()->closeTag(); ?>

    <h3>Вакансии</h3>

    <table class="table">
        <thead>
        <th class="col-md-3">Департамент</th>
        <th class="col-md-9">Наименование вакансии</th>
        </thead>
        <tbody>
    <?php foreach($this->jobs as $job) : $translation = $job->getTranslation($this->language); ?>

        <tr>
            <td><?php echo $job->getDepartment()->getName();?></td>
            <td><?php echo $translation->getName();?></td>

        </tr>


    <?php endforeach?>
        </tbody>
    </table>
